format = """
[î‚¶](#9A348E)\
$username\
[î‚´](bg:#DA627D fg:#9A348E)\
$directory\
[î‚´](fg:#DA627D bg:#FAFAFA)\
$git_branch\
$git_status\
[î‚´](fg:#FAFAFA bg:#86BBD8)\
$nodejs\
$rust\
$golang\
[î‚´](fg:#86BBD8 bg:#33658A)\
$time\
[î‚´ ](fg:#33658A)\
$line_break\
$character\
"""

# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[ğŸ§” $user ]($style)'

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vicmd_symbol = "[â®](green)"

[directory]
style = "bg:#DA627D"
format = "[ $path]($style)[$read_only ]($read_only_style bg:#DA627D)"
read_only = "ğŸ”’"
home_symbol = "ğŸ "
#truncation_length = 5
#truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"Videos" = "ï€½ "
"dev" = "ï„¡ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[git_branch]
symbol = "ï˜"
style = "bg:#FAFAFA fg:#FCA17D"
format = '[[ $symbol $branch ]($style)]($style)'

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨ â‡¡${count}"
behind = "ğŸ˜°â‡£${count}"
diverged = "ğŸ˜µâ‡¡${ahead_count}â‡£${behind_count}"
up_to_date = "âœ…"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "ğŸ‘"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
style = "bg:#FAFAFA"
format = '[[($all_status$ahead_behind )]($style)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[rust]
symbol = "î¨"
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[golang]
symbol = "î˜§"
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[java]
symbol = "îœ¸"
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[ ğŸ’• $time ](bg:#33658A)]($style)'
