[aws]
format = '[$symbol($profile)(\($region\))($duration)]($style)'
symbol = "îŒ½  "

[character]
success_symbol = "[â””â•¼](red)[ â¯](bright yellow)"
error_symbol = "[â””â•¼](red)[ â¯](red)"
vicmd_symbol = "[â””â•¼](red)[ â®](green)"

[cmake]
format = '[$symbol($version)]($style)'
symbol = "î˜ "

[cmd_duration]
format = ' took [\[](red)[â±  $duration]($style)[\]](red)'

[cobol]
format = '[$symbol($version)]($style)'

[conda]
format = '[$symbol$environment]($style)'
symbol = "ï„Œ "

[crystal]
format = '[$symbol($version)]($style)'

[dart]
format = '[$symbol($version)]($style)'
symbol = "î˜ "

[deno]
format = '[$symbol($version)]($style)'

[directory]
read_only = " ï ½ "
home_symbol = "ï€• "
truncate_to_repo = false
format = "[\\]-\\[](red)[$path]($style)[$read_only]($read_only_style)[\\]](red)"

[docker_context]
format = '[$symbol$context]($style)'
symbol = "ïŒˆ "

[dotnet]
format = '[$symbol($version)(ğŸ¯ $tfm)]($style)'

[elixir]
format = '[$symbol($version \(OTP $otp_version\))]($style)'
symbol = "î‰µ "

[elm]
format = '[$symbol($version)]($style)'
symbol = "î˜¬ "

[erlang]
format = '[$symbol($version)]($style)'
symbol = "î± : "

[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style)'
symbol = "î² "

[git_branch]
format = '[ + \[$symbol$branch\]]($style)'
symbol = "ï˜ "

[git_status]
format = '[\[$all_status$ahead_behind\]]($style)'
conflicted = "ï€¤ "
ahead = "ï‚ª ${count}"
behind = "ï‚« ${count}"
diverged = "ï—º "
up_to_date = '[ï˜ ](green)'
untracked = "ï™ "
stashed = '[ï€œ ](yellow)'
modified = "ïª "
staged = '[ï• \($count\)](green)'
renamed = "ï‘š "
deleted = "ï’ "

[golang]
format = '[$symbol($version)]($style)'
symbol = "î˜§ "

#[haskell]
#format = '[$symbol($version)]($style)'
#symbol = "î· "

[helm]
format = '[$symbol($version)]($style)'

[hg_branch]
format = '[$symbol$branch]($style)'
symbol = "ï˜ "

[hostname]
ssh_only = true
format = "@[$hostname](bold blue)"

[java]
format = '[$symbol($version)]($style)'
symbol = "î‰– "

[julia]
format = '[$symbol($version)]($style)'
symbol = "î˜¤ "

[kotlin]
format = '[$symbol($version)]($style)'

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style)'

[lua]
format = '[ + \[](red)[$symbol($version)]($style)[\]](red)'
symbol = "î˜  "

[memory_usage]
format = '$symbol[$ram( | $swap)]($style)'
symbol = "ï¡š "

[nim]
format = '[$symbol($version)]($style)'
symbol = "ïš¤ "

[nix_shell]
format = '[$symbol$state( \($name\))]($style)'
symbol = "ï‹œ "

[nodejs]
format = '[$symbol($version)]($style)'
symbol = "îœ˜ "

[ocaml]
format = '[$symbol($version)(\($switch_indicator$switch_name\))]($style)'

[openstack]
format = '[$symbol$cloud(\($project\))]($style)'

[package]
format = '[$symbol$version]($style)'
symbol = "ï£– "

[perl]
format = '[$symbol($version)]($style)'
symbol = "î© "

[php]
format = '[$symbol($version)]($style)'
symbol = "ï  "

[pulumi]
format = '[$symbol$stack]($style)'

[purescript]
format = '[$symbol($version)]($style)'

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'
symbol = "îœ¼ "

[red]
format = '[$symbol($version)]($style)'

[ruby]
format = '[$symbol($version)]($style)'
symbol = "î‘ "

[rust]
format = '[$symbol($version)]($style)'
symbol = "î¨ "

[scala]
format = '[$symbol($version)]($style)'
symbol = "îœ· "

[sudo]
format = '[as $symbol]'

[swift]
format = '[$symbol($version)]($style)'
symbol = "î• "

[terraform]
format = '[$symbol$workspace]($style)'

[time]
format = '[$time]($style)'

[username]
format = '[â”Œ\[](red)[ïŠ½  $user]($style_user)'
show_always = true

[vagrant]
format = '[$symbol($version)]($style)'

[vlang]
format = '[$symbol($version)]($style)'

[zig]
format = '[$symbol($version)]($style)'
